import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from './providers';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Todo App",
  description: "Generated by create next app with integrated with mongoose and graphql",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers initialApolloState={{}}>
          {children}
        </Providers>
      </body>
    </html>
  );
}