name: Build simple nextjs app
on: push
jobs:
  build: 
    name: build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install npm dependencies
      run: npm install --legacy-peer-deps
    - name: Build project assets
      run: npm run build
